### ISSUE TITLE
Multi cert functionality

### ISSUE THREAD

**Issue by fayeg21** [krtab/agnos#30]
It would be great if this tool's config was easily used to create multiple separated certs for separate domain names.

i.e. something like this:
```
[[accounts.certificates]]
{
domains = ["*.foo.com"]
fullchain_output_file = "/etc/ssl/certs/foo.com.pem"
key_output_file = "/etc/ssl/private/foo.com.pem"
},
{
domains = ["*.bar.com"]
fullchain_output_file = "/etc/ssl/certs/bar.com.pem"
key_output_file = "/etc/ssl/private/bar.com.pem"
},
```

**Comment by justinas** [comment]
Hmm, perhaps you're confused about the TOML syntax? This:

```toml
[[accounts.certificates]]
domains = ["*.foo.com"]
fullchain_output_file = "/etc/ssl/certs/foo.com.pem"
key_output_file = "/etc/ssl/private/foo.com.pem"

[[accounts.certificates]]
domains = ["*.bar.com"]
fullchain_output_file = "/etc/ssl/certs/bar.com.pem"
key_output_file = "/etc/ssl/private/bar.com.pem"
```

should do what you want (one account, two `certificates`). You can check with a [TOML to JSON converter](https://pseitz.github.io/toml-to-json-online-converter/), JSON might be easier to understand.
